<table id="<?=$this->rawControlId?>">
	<tbody>
		<tr>

			<? if ($this->page > 1): ?>
				<td>
					<a href="<?
						echo $this->grid->getUrl(
							$this->page - 1,
							'page'
						);
					?>"><?=$this->translate('previous')?></a>
				</td>
			<? endif; ?>

			<? foreach ($this->steps as $stepKey => $step): ?>
				<td>
					<? if ($step == $this->page): ?>
						<b><?=$step?></b>
					<? else: ?>
						<a href="<?
							echo $this->grid->getUrl(
								$step,
								'page'
							);
						?>"><?=$step?></a>
					<? endif; ?>
					&nbsp;&nbsp;
				</td>
			<? endforeach; ?>

			<? if ($this->page < $this->pagesCount): ?>
				<td>
					<a href="<?
						echo $this->grid->getUrl(
							$this->page + 1,
							'page'
						);
					?>"><?=$this->translate('next')?></a>
				</td>
			<? endif; ?>

		</tr>
	</tbody>
</table>