<?php
	/** @var $this \MvcCore\Ext\Controllers\DataGrids\View */
	/** @var $grid \MvcCore\Ext\Controllers\DataGrid */
?><table class="grid-control-counts"><tbody><?php
	$countScales = $grid->GetCountScales();
	$itemsPerPage = $grid->GetItemsPerPage();
	foreach ($countScales as $countScale):
		$current = $countScale === $itemsPerPage;
		?><td class="grid-count<?php
			if ($current) echo ' grid-count-current';
		?>"><?php

			$text = ($countScale === 0)
				? 'All'
				: (string) $countScale;

			if ($current):
				?><span class="grid-count-current"><?php
					echo $text;
				?></span><?php
			else:
				?><a class="grid-count-link" href="<?php
					echo $grid->GridCountUrl($countScale);
				?>"><?php
					echo $text;
				?></a><?php
			endif;

		?></td><?php
		
	endforeach;
?></tr></table>