<?php
	/** @var $this \MvcCore\Ext\Controllers\DataGrids\View */
	/** @var $grid \MvcCore\Ext\Controllers\DataGrid */
?><table class="grid-control-order"><tbody><?php
	$ordering = $grid->GetOrdering();
	$configColumns = $grid->GetConfigColumns();
	foreach ($configColumns as $urlName => $configColumn):
		if (!$configColumn->GetOrder()) continue;
		
		?><td class="<?php echo 'grid-control-order-' . $configColumn->GetUrlName(); ?>"><?php

			?><a class="grid-control-order-link" href="<?php
				echo $grid->GridOrderUrl($configColumn);
			?>"><?php
				echo $configColumn->GetHumanName();
			?></a><?php

			$dir = $grid->GetColumnOrderDirection($configColumn);
			if ($dir !== NULL): 
				?><span class="grid-control-order-dir grid-control-order-<?php
					echo $dir ? 'asc' : 'desc';
				?>"><?php
					echo $dir ? '&#9660;' : '&#9650;';
				?></span><?php

				if ($grid->GetMultiSorting()):
					$orderIndex = $grid->GetColumnOrderIndex($configColumn);
					if ($orderIndex !== NULL):
						?><span class="grid-control-order-index"><?php
							echo $orderIndex + 1;
						?></span><?php
					endif;
				endif;
			endif;

		?></td><?php
		
	endforeach;
?></tr></table>