<?php
	/** @var $this \MvcCore\Ext\Controllers\DataGrids\View */
	/** @var $grid \MvcCore\Ext\Controllers\DataGrid */
?><table class="grid-control-pages"><tbody><?php
	foreach ($grid->GetPaging() as $pagingItem):
		
		?><td class="grid-page<?php
			if ($pagingItem->IsEmpty()):
				echo ' grid-page-space';
			elseif ($pagingItem->IsCurrent()):
				echo ' grid-page-current';
			else:
				echo ' grid-page-link';
			endif;
		?>"><?php

		if ($pagingItem->IsEmpty()):
			?><span>&hellip;</span><?php
		elseif ($pagingItem->IsCurrent()):
			?><span><?php
				echo $pagingItem->GetText();
			?></span><?php
		else:
			?><a href="<?php
				echo $pagingItem->GetUrl();
			?>"><span><?php
				echo $pagingItem->GetText();
			?></span></a><?php
		endif;

		?></td><?php
		
	endforeach;
?></tr></table>