<?php
	/** @var $this \MvcCore\Ext\Controllers\DataGrids\View */
	/** @var $grid \MvcCore\Ext\Controllers\DataGrid */
?><table class="grid-control-pages"><tbody><?php
	foreach ($grid->GetPaging() as $pagingItem):
		
		?><td class="grid-page <?php
			echo $pagingItem->GetCssClass();
		?>"><?php

		if ($pagingItem instanceof \MvcCore\Ext\Controllers\DataGrids\Paging\Dot):
			?><span><?php echo $pagingItem->GetText(); ?></span><?php
		elseif ($pagingItem->IsCurrent()):
			?><span><?php
				echo $pagingItem->GetText();
			?></span><?php
		else:
			?><a href="<?php
				echo $pagingItem->GetUrl();
			?>"><span><?php
				echo $pagingItem->GetText();
			?></span></a><?php
		endif;

		?></td><?php
		
	endforeach;
?></tr></table>