<?php
	/** @var $this \MvcCore\Ext\Controllers\DataGrids\View */
	/** @var $grid \MvcCore\Ext\Controllers\DataGrid */

	$pagingItems = $grid->GetPaging();
	$renderConf = $this->GetConfigRendering();
	$pagingCssClasses = $renderConf->GetCssClassesControlPaging();
	$pagingCssClasses[] = 'grid-control-items-count-' . count($pagingItems);

?><table<?php
	if (count($pagingCssClasses) > 0)
		echo ' class="' . implode(' ', $pagingCssClasses) . '"';
?>><tbody><?php
	foreach ($pagingItems as $pagingItem):
		
		?><td class="grid-page <?php
			echo $pagingItem->GetCssClass();
		?>"><?php

		if ($pagingItem instanceof \MvcCore\Ext\Controllers\DataGrids\Paging\Dot):
			?><span><?php echo $pagingItem->GetText(); ?></span><?php
		elseif ($pagingItem->IsCurrent()):
			?><span><?php
				echo $pagingItem->GetText();
			?></span><?php
		else:
			?><a href="<?php
				echo $pagingItem->GetUrl();
			?>"><span><?php
				echo $pagingItem->GetText();
			?></span></a><?php
		endif;

		?></td><?php
		
	endforeach;
?></tr></table>