<?php
	/** @var \MvcCore\Ext\Controllers\DataGrids\View $this */
	/** @var \MvcCore\Ext\Controllers\DataGrid $grid */

	$renderConf = $this->GetConfigRendering();
	$sortingCssClasses = $renderConf->GetCssClassesControlSorting();
	$configColumns = $grid->GetConfigColumns();
	$configColumns2Render = [];
	foreach ($configColumns as $urlName => $configColumn):
		if ($configColumn->GetSort()) 
			$configColumns2Render[$urlName] = $configColumn;
	endforeach;
	$miltiSort = ($grid->GetSortingMode() & $grid::SORT_MULTIPLE_COLUMNS) != 0;
	$sortingCssClasses[] = 'grid-control-items-count-' . count($configColumns2Render);

?><table<?php
	if (count($sortingCssClasses) > 0)
		echo ' class="' . implode(' ', $sortingCssClasses) . '"';
?>><tbody><?php
	foreach ($configColumns2Render as $urlName => $configColumn):
		?><td class="<?php echo 'grid-control-sort-' . $configColumn->GetUrlName(); ?>"><?php

			?><a class="grid-control-sort-link" href="<?php
				echo $grid->GridSortUrl($configColumn);
			?>"><?php
				echo $configColumn->GetHumanName();
			?></a><?php

			$dir = $grid->GetColumnSortDirection($configColumn);
			if ($dir !== NULL): 
				?><span class="grid-control-sort-dir grid-control-sort-<?php
					echo $dir ? 'asc' : 'desc';
				?>"><?php
					echo $dir ? '&#9660;' : '&#9650;';
				?></span><?php

				if ($miltiSort):
					$sortIndex = $grid->GetColumnSortIndex($configColumn);
					if ($sortIndex !== NULL):
						?><span class="grid-control-sort-index"><?php
							echo $sortIndex + 1;
						?></span><?php
					endif;
				endif;
			endif;

		?></td><?php
		
	endforeach;
?></tr></table>