<?php
	/** @var \MvcCore\Ext\Controllers\DataGrids\View $this */
	/** @var \MvcCore\Ext\Controllers\DataGrid $grid */
	/** @var \MvcCore\Ext\Controllers\DataGrids\Models\GridModel $model */

	$renderConf = $grid->GetConfigRendering();
	$colsCount = $renderConf->GetGridColumnsCount();
	$model = $grid->GetModel();
	$colIndex = 0;

?><tbody>
	<tr class="grid-row-odd"><?php

		foreach ($grid->GetPageData() as $index => $item):
			$colNumber = $colIndex % $colsCount;

			if ($colIndex > 0 && $colNumber === 0):
				?></tr><tr class="grid-row-<?php
					echo ($index % 2 === 0 ? 'odd' : 'even');
				?>"><?php
			endif;

			?><td class="grid-column-<?php echo $colNumber + 1; ?>"><?php
		
				foreach ($grid->GetConfigColumns(TRUE) as $configColumn):
					?><div class="grid-cell-content <?php
						echo implode(' ', $configColumn->GetCssClasses());
					?>"><?php
					
					$renderedCell = trim($model->RenderCell($item, $configColumn, $this));
					if (mb_strlen($renderedCell) > 0):
						$columnUrlHelper = $configColumn->GetUrlHelper();

						if (is_string($columnUrlHelper) && strlen($columnUrlHelper) > 0):
							?><a class="grid-custom-link" href="<?php
								echo $item->{$columnUrlHelper}();
							?>"><?php
								echo $this->EscapeHtml($renderedCell);
							?></a><?php
						elseif ($columnUrlHelper && $configColumn->GetFilter()):
							?><a class="grid-filter-link" href="<?php
								echo $grid->GridFilterUrl(
									$configColumn,
									$model->GetFilterUrlValue($item, $configColumn)
								);
							?>"><?php
								echo $this->EscapeHtml($renderedCell);
							?></a><?php
						else:
							echo $this->EscapeHtml($renderedCell);
						endif;

					endif;

					?></div><?php
				endforeach;

			?></td><?php
			$colIndex++;

		endforeach;
	
		if ($colsCount > 1):
			for ($i = $colIndex % $colsCount; $i < $colsCount; $i++):
				?><td class="grid-column-<?php echo $i + 1; ?> grid-cell-empty"></td><?php
			endfor;
		endif;

	?></tr>
</tbody>