<?php
	/** @var \MvcCore\Ext\Controllers\DataGrids\View $this */
	/** @var \MvcCore\Ext\Controllers\DataGrid $grid */

	$renderConf = $grid->GetConfigRendering();
	$gridType = $renderConf->GetType();
	$gridTableType = ($gridType & $grid::TYPE_TABLE) !== 0;
	$gridCssClasses = $grid->GetCssClasses();
	$contentTableCssClasses = $renderConf->GetCssClassesContentTable();
	$controlsWrapperCssClasses = $renderConf->GetCssClassesControlsWrapper();
	$controlsWrapperCssClass = count($controlsWrapperCssClasses) > 0
		? implode(' ', $controlsWrapperCssClasses)
		: '';
	$controlFilterForm = $renderConf->GetRenderFilterForm();
	$headFiltering = $renderConf->GetRenderTableHeadFiltering();
	if ($controlFilterForm) 
		echo $this->RenderGridFilterForm();

?><div<?php
	if (count($gridCssClasses) > 0) 
		echo ' class="'.implode(' ', $gridCssClasses) . '"';
?>><?php
	if ($renderConf->GetRenderControlPaging() || $renderConf->GetRenderControlSorting()):
	?><div class="<?php echo $controlsWrapperCssClass; ?> grid-controls-top"><?php
		$pagingCode = $this->RenderGridControlPaging();
		echo $pagingCode;
		echo $this->RenderGridControlSorting();
	?></div><?php
	endif;
	if ($headFiltering):
		$headForm = $grid->GetTableHeadFilterForm();
		echo $headForm->RenderBegin();
	endif;
	?><table<?php
		if (count($contentTableCssClasses) > 0) 
			echo ' class="'.implode(' ', $contentTableCssClasses) . '"';
	?>><?php
		if ($gridTableType): 
			echo $this->RenderGridHeadTable();
			echo $this->RenderGridBodyTable();
		else:
			echo $this->RenderGridBodyGrid();
		endif;
	?></table><?php
	if ($headFiltering):
		echo $headForm->RenderEnd();
	endif;
	if ($renderConf->GetRenderControlStatus() || $renderConf->GetRenderControlPaging() || $renderConf->GetRenderControlCountScales()):
	?><div class="<?php echo $controlsWrapperCssClass; ?> grid-controls-bottom"><?php 
		echo $this->RenderGridControlStatus();
		if (isset($pagingCode)) echo $pagingCode;
		echo $this->RenderGridControlCountScales();
	?></div><?php
	endif;
?></div>