<?php
	/** @var $this \MvcCore\Ext\Controllers\DataGrids\View */
	/** @var $grid \MvcCore\Ext\Controllers\DataGrid */
?><thead><tr><td<?php
	$renderConf = $grid->GetConfigRendering();
	$colsCount = $renderConf->GetGridColumnsCount();
	if ($colsCount > 1) echo ' colspan="'.$colsCount.'"';
?>><table class="datagrid-head"><tbody><tr><?php
	$ordering = $grid->GetOrdering();
	$configColumns = $grid->GetConfigColumns();
	foreach ($configColumns as $urlName => $configColumn):
		
		?><th class="<?php
			echo 'grid-col-' . $configColumn->GetUrlName();
			if ($grid->GetColumnFiltered($configColumn) !== NULL):
				echo ' grid-col-filtering';
			endif;
		?>"><?php

		if ($configColumn->GetOrder()): 

			?><a class="grid-order-link" href="<?php
				echo $grid->GridOrderUrl($configColumn);
			?>"><?php
				echo $configColumn->GetHumanName();
			?></a><?php

			$dir = $grid->GetColumnOrderDirection($configColumn);
			if ($dir !== NULL): 
				?><span class="grid-order-dir grid-order-<?php
					echo $dir ? 'asc' : 'desc';
				?>"><?php
					echo $dir ? '&#9660;' : '&#9650;';
				?></span><?php

				if ($grid->GetMultiSorting()):
					$orderIndex = $grid->GetColumnOrderIndex($configColumn);
					if ($orderIndex !== NULL):
						?><span class="grid-order-index"><?php
							echo $orderIndex + 1;
						?></span><?php
					endif;
				endif;
			endif;

		else:

			?><span class="grid-head-text"><?php
				echo $configColumn->GetHumanName();
			?></span><?php

		endif;
		?></th><?php
		
	endforeach;
?></tr></tbody></table></td></tr></thead>