<?php
	/** @var \MvcCore\Ext\Controllers\DataGrids\View $this */
	/** @var \MvcCore\Ext\Controllers\DataGrid $grid */
	/** @var \MvcCore\Ext\Controllers\DataGrids\Models\GridModel $model */
?><tbody><?php
	
	$renderConf = $grid->GetConfigRendering();
	$colsCount = $renderConf->GetGridColumnsCount();
	$model = $grid->GetModel();
	$colIndex = 0;

	?><tr class="grid-row-odd"><?php
	foreach ($grid->GetPageData() as $index => $item):
	
		$colNumber = $colIndex % $colsCount;
		if ($colIndex > 0 && $colNumber === 0):
			?></tr><tr class="grid-row-<?php
				echo ($index % 2 === 0 ? 'odd' : 'even');
			?>"><?php
		endif;
		
		?><td class="grid-column-<?php echo $colNumber + 1; ?>"><?php
		
			foreach ($grid->GetConfigColumns() as $configColumn):
				?><div class="grid-cell-content <?php
					echo implode(' ', $configColumn->GetCssClasses());
				?>"><?php
					
				$cellValue = trim($model->RenderCell($item, $configColumn, $this));
				if (mb_strlen($cellValue) > 0):
					if ($configColumn->GetFilter()):
						?><a class="grid-filter-link" href="<?php
							echo $grid->GridFilterUrl($configColumn, $cellValue);
						?>"><?php
							echo $cellValue;
						?></a><?php
					else:
						echo $cellValue;
					endif;
				endif;

				?></div><?php
			endforeach;

		?></td><?php

		$colIndex++;
	endforeach;
	
	if ($colsCount > 1):
		for ($i = $colIndex % $colsCount; $i < $colsCount; $i++):
			?><td class="grid-column-<?php echo $i + 1; ?> grid-cell-empty"></td><?php
		endfor;
	endif;

	?></tr><?php

?></tbody>