<?php
	/** @var $this \MvcCore\Ext\Controllers\DataGrids\View */
	/** @var $grid \MvcCore\Ext\Controllers\DataGrid */
?><thead><tr><?php
	
	$configColumns = $grid->GetConfigColumns();
	$gridSortingMode = $grid->GetSortingMode();
	$sortAllowed = $gridSortingMode > $grid::SORT_DISABLED;
	$miltiSort = ($gridSortingMode & $grid::SORT_MULTIPLE_COLUMNS) != 0;
	$renderConf = $grid->GetConfigRendering();
	$headSort = $sortAllowed && $renderConf->GetRenderTableHeadSorting();
	$headFilter = $renderConf->GetRenderTableHeadFiltering();
	$headForm = $headFilter ? $grid->GetTableHeadFilterForm() : NULL;
	foreach ($configColumns as $urlName => $configColumn):
		
		?><th class="<?php
			echo 'grid-col-' . $configColumn->GetUrlName();
			if ($grid->GetColumnFilterIndex($configColumn) !== FALSE)
				echo ' grid-col-filtered';
		?>"><?php

		if ($headFilter):
			?><div class="grid-head-sort"><?php
		endif;
		
		if ($headSort && $configColumn->GetSort()): 
			?><a class="grid-head-sort-link" href="<?php
				echo $grid->GridSortUrl($configColumn);
			?>"><?php
				echo $configColumn->GetHumanName();
			?></a><?php

			$dir = $grid->GetColumnSortDirection($configColumn);
			if ($dir !== NULL): 
				?><span class="grid-head-sort-dir grid-head-sort-<?php
					echo $dir ? 'asc' : 'desc';
				?>"><?php
					echo $dir ? '&#9660;' : '&#9650;';
				?></span><?php

				if ($miltiSort):
					$sortIndex = $grid->GetColumnSortIndex($configColumn);
					if ($sortIndex !== NULL):
						?><span class="grid-head-sort-index"><?php
							echo $sortIndex + 1;
						?></span><?php
					endif;
				endif;
			endif;

		else:

			?><span class="grid-head-text"><?php
				echo $configColumn->GetHumanName();
			?></span><?php

		endif;

		if ($headFilter):
			?></div><?php
			if ($configColumn->GetFilter()):
				$valueField = $headForm->GetField(implode($headForm::HTML_IDS_DELIMITER, ['value', $urlName]));
				$filterField = $headForm->GetField(implode($headForm::HTML_IDS_DELIMITER, ['filter', $urlName]));
				$clearField = $headForm->GetField(implode($headForm::HTML_IDS_DELIMITER, ['clear', $urlName]));
				?><div class="grid-head-filter"><?php
					echo $valueField->RenderControl();
					echo $filterField->RenderControl();
					echo $clearField->RenderControl();
				?></div><?php
			endif;
		endif;

		?></th><?php
		
	endforeach;
?></tr></thead>