<?php
	/**
	 * @var \MvcCore\Ext\Controllers\DataGrids\View $this
	 * @var \MvcCore\Ext\Controllers\DataGrid $grid
	 * @var \MvcCore\Ext\Controllers\DataGrids\Models\GridModel $model
	 * @var \MvcCore\Ext\Controllers\DataGrids\Models\GridRow $item
	 */
	$model = $grid->GetModel();
	$renderConf = $grid->GetConfigRendering();
	$renderFilteringLinks = $renderConf->GetRenderTableBodyFilteringLinks();
?><tbody><?php

	foreach ($grid->GetPageData() as $index => $item):
		$item->SetGrid($grid);
		?><tr class="<?php
			echo 'grid-row-' . ($index % 2 === 0 ? 'odd' : 'even');
		?>"><?php

			foreach ($grid->GetConfigColumns(TRUE) as $configColumn):
				?><td class="<?php
					echo implode(' ', $configColumn->GetCssClasses());
				?>"><?php
					
					$renderedCell = $item->RenderCell($configColumn, $this);
					$renderedCell = $renderedCell === NULL ? '' : trim($renderedCell);
					if (mb_strlen($renderedCell) > 0):
						$columnUrlHelper = $configColumn->GetUrlHelper();
						
						if (is_string($columnUrlHelper) && strlen($columnUrlHelper) > 0):
							?><a class="grid-cell-content grid-custom-link" href="<?php
								echo $this->EscapeAttr($item->{$columnUrlHelper}());
							?>"><?php
								echo $this->EscapeHtml($renderedCell);
							?></a><?php

						elseif ($renderFilteringLinks && $columnUrlHelper && $configColumn->GetFilter()):
							?><a class="grid-cell-content grid-filter-link" href="<?php
								echo $this->EscapeAttr($grid->GridFilterUrl($configColumn, $renderedCell));
							?>"><?php
								echo $this->EscapeHtml($renderedCell);
							?></a><?php

						else:
							?><span class="grid-cell-content"><?php
								echo $this->EscapeHtml($renderedCell);
							?></span><?php 
						endif;

					endif;
				?></td><?php
			endforeach;

		?></tr><?php
	endforeach;

?></tbody>