<?php
	/** @var $this \MvcCore\Ext\Controllers\DataGrids\View */
	/** @var $grid \MvcCore\Ext\Controllers\DataGrid */
?><thead><tr><?php
	$ordering = $grid->GetOrdering();
	$configColumns = $grid->GetConfigColumns();
	$headFiltering = $grid->GetConfigRendering()->GetRenderTableHeadFiltering();
	$headForm = $headFiltering ? $grid->GetTableHeadFilterForm() : NULL;
	foreach ($configColumns as $urlName => $configColumn):
		
		?><th class="<?php
			echo 'grid-col-' . $configColumn->GetUrlName();
			if ($grid->GetColumnFiltered($configColumn) !== NULL)
				echo ' grid-col-filtered';
		?>"><?php

		if ($headFiltering):
			?><div class="grid-head-order"><?php
		endif;

		if ($configColumn->GetOrder()): 

			?><a class="grid-head-order-link" href="<?php
				echo $grid->GridOrderUrl($configColumn);
			?>"><?php
				echo $configColumn->GetHumanName();
			?></a><?php

			$dir = $grid->GetColumnOrderDirection($configColumn);
			if ($dir !== NULL): 
				?><span class="grid-head-order-dir grid-head-order-<?php
					echo $dir ? 'asc' : 'desc';
				?>"><?php
					echo $dir ? '&#9660;' : '&#9650;';
				?></span><?php

				if ($grid->GetMultiSorting()):
					$orderIndex = $grid->GetColumnOrderIndex($configColumn);
					if ($orderIndex !== NULL):
						?><span class="grid-head-order-index"><?php
							echo $orderIndex + 1;
						?></span><?php
					endif;
				endif;
			endif;

		else:

			?><span class="grid-head-text"><?php
				echo $configColumn->GetHumanName();
			?></span><?php

		endif;

		if ($headFiltering):
			?></div><?php
			if ($configColumn->GetFilter()):
				$filterField = $headForm->GetField(implode($headForm::HTML_IDS_DELIMITER, ['filter', $urlName]));
				$submitField = $headForm->GetField(implode($headForm::HTML_IDS_DELIMITER, ['submit', $urlName]));
				?><div class="grid-head-filter"><?php
					echo $filterField->RenderControl();
					echo $submitField->RenderControl();
				?></div><?php
			endif;
		endif;

		?></th><?php
		
	endforeach;
?></tr></thead>