<?php
	/** @var \MvcCore\Ext\Controllers\DataGrids\View $this */
	/** @var \MvcCore\Ext\Controllers\DataGrid $grid */
	/** @var \MvcCore\Ext\Controllers\DataGrids\Models\GridModel $model */
?><tbody><?php

	$model = $grid->GetModel();
	foreach ($grid->GetPageData() as $index => $item):

		?><tr class="<?php
			echo 'grid-row-' . ($index % 2 === 0 ? 'odd' : 'even');
		?>"><?php

			foreach ($grid->GetConfigColumns() as $configColumn):
				?><td class="<?php
					echo implode(' ', $configColumn->GetCssClasses());
				?>"><?php
					
				$cellValue = trim($model->RenderCell($item, $configColumn, $this));
				if (mb_strlen($cellValue) > 0):
					if ($configColumn->GetFilter()):
						?><a class="grid-cell-content grid-filter-link" href="<?php
							echo $grid->GridFilterUrl($configColumn, $cellValue);
						?>"><?php
							echo $this->EscapeHtml($cellValue);
						?></a><?php
					else:
						?><span class="grid-cell-content"><?php echo $this->EscapeHtml($cellValue); ?></span><?php 
					endif;
				endif;

				?></td><?php
			endforeach;

		?></tr><?php
	endforeach;

?></tbody>